### ISSUE TITLE
Add Modelica specification to the templates

### ISSUE THREAD

**Issue by tbeu** [modelica-association/conference-templates#10]
It would be very convenient if the versions of the MLS v3.2 rev 2 and MLS v3.3 rev 1 are part of the example-paper.bib (and also Word template).

I found some examples where it is as used as Misc or Manual. A consistent style would be helpful for the templates.

* https://github.com/giorgidze/thesis_phd/blob/master/main.bib#L623-L630

* https://github.com/havelund/isola-2016-unified-introduction/blob/master/bib.bib#L288-L293

* https://github.com/modelica/Modelica_DeviceDrivers/blob/modelica2017/Modelica_DeviceDrivers/Resources/doc/Modelica2017/modelica2017_Modelica_DeviceDrivers.bib#L86-L96

**Comment by tbeu** [comment]
Also MLS v3.4 would be nice to have in the example bib file.

**Comment by akloeckner** [comment]
Another possibility: @TechReport...
- Misc
- Manual
- Techreport


```
 @TECHREPORT{modelica2014modelica,
  author = {{Modelica Association}},
  title = {{M}odelica -- A Unified Object-Oriented Language for Systems Modeling.
	{L}anguage Specification Version 3.3 Revision 1},
  institution = {Modelica Association},
  year = {2014},
  address = {Link{\"o}ping},
  month = {July 11},
  abstract = {This document defines the Modelica1 language, version 3.3, which is
	developed by the Modelica Association, a non-profit organization
	with seat in Linköping, Sweden. Modelica is a freely available, object-oriented
	language for modeling of large, complex, and heterogeneous systems.
	It is suited for multi-domain modeling, for example, mechatronic
	models in robotics, automotive and aerospace applications involving
	mechanical, electrical, hydraulic control and state machine subsystems,
	process oriented applications and generation and distribution of
	electric power. Models in Modelica are mathematically described by
	differential, algebraic and discrete equations. No particular variable
	needs to be solved for manually. A Modelica tool will have enough
	information to decide that automatically. Modelica is designed such
	that available, specialized algorithms can be utilized to enable
	efficient handling of large models having more than one hundred thousand
	equations. Modelica is suited and used for hardware-in-the-loop simulations
	and for embedded control systems. More information is available at
	http://www.Modelica.org/
	
	
	Version 3.3 Revision 1 clarifies and fixes issues of the specification
	text. In particular it includes all updates made in Version 3.2 Revision
	2.},
 }
```

Do we want a discussion about the correct entry? Or is it more convenient, if someone could provide a pull request for entries MSLv32r2, MSLv33r1 and MSLv34? Improvements can then also be supplied as PRs...

**Comment by akloeckner** [comment]
I just gave it a try and put the MSL specs in the bib file: https://github.com/akloeckner/conference-templates/commit/1d570cd016ebe7d6849440b69800008813dd2c8b

Is that what you had in mind?

**Comment by akloeckner** [comment]
I'm closing the issue, as PR #16 addressing it has been accepted.

**Comment by tbeu** [comment]
The standard papers for FMI 1.0 and 2.0 would also be nice to have.
