### ISSUE TITLE
Why bother and not simply switch to IEEE conference template?

### ISSUE THREAD

**Issue by dietmarw** [modelica-association/conference-templates#15]
That would save a lot of work and many people are used to those templates which also are well documented in addition. So why not simply using those for future conferences (and adding a sane listing definition for modelica code to it)

https://www.ieee.org/conferences_events/conferences/publishing/templates.html

(I'm aware that this is probably something to decide on by the Modelica Association as a whole.)

**Comment by casella** [comment]
It seems that the Board is more comfortable with Harward-style references. De gustibus...

**Comment by dietmarw** [comment]
Well I was actually talking about the **whole** template. Not just the bibliography.

**Comment by bernhard-thiele** [comment]
Another template that seems to be free to use and which I think is looking rather attractive is provided by the MIC journal: http://www.mic-journal.no/micauthors.asp

That one also has Harvard-style references as default.

**Comment by dietmarw** [comment]
Yes I thought if MIC (naturally) too, problem here is we have to come up with the Word template in addition. MIC only does LaTeX (bless them).

**Comment by casella** [comment]
Why don't we just keep on adjusting our template incrementally? I think what I inherited from the Versailles conference was already quite good. We made some further adjustments for this conference, and we'll make some more for the next one. Anything wrong with that?

**Comment by dietmarw** [comment]
It would be nice **not** having to do the adjustments and simply stick to some established standard. Sounds familiar? ;-)

**Comment by casella** [comment]
That depends on your definition of standard. ieeetrans.cls dates back to 2006 and seems to be no longer maintained, at least that was the situation some time ago.
Anyway, sticking to a standard is good, as long as it is _our_ standard ;)

**Comment by dietmarw** [comment]
I'm actually less worried about the LaTeX template since that is fixable in an easy and **controlled** fashion. It's more the Word template that needs to follow and I won't touch that with a long poker stick.

**Comment by sjoelund** [comment]
> I'm actually less worried about the LaTeX template since that is fixable in an easy and **controlled** fashion. It's more the Word template that needs to follow and I won't touch that with a long poker stick.

I think it was now decided to have the LaTeX template be the master and people write in Word should follow it. The current Word template was generated from the LaTeX PDF if I understood it correctly (#22).

And for 2021, we have biblatex and some more things changed. It should still be improved, but I guess we can resolve this issue?

**Comment by dietmarw** [comment]
Fine for me as long as the LaTeX template is the main reference. Which it seems is the status now. So feel free to close.
