### ISSUE TITLE
Plain template causes conflicting options warning in biblatex.

### ISSUE THREAD

**Issue by dietmarw** [modelica-association/conference-templates#28]
Not quite sure what is causing this but the template is currently triggering this warning:
```
Package biblatex Warning: Conflicting options. 'date=iso' requires 'seconds=true'. Setting 'seconds=true' on input line 42.
```
See also https://www.overleaf.com/read/vjkbztzgmnnc

**Comment by sjoelund** [comment]
You could add `seconds=true` here to silence the warning: https://github.com/modelica-association/conference-templates/blob/master/LaTeX/modelica.cls#L100

I'm not sure why it thinks it is conflicting options though. Nothing in the options set it to false as far as I can tell.

**Comment by dietmarw** [comment]
Yes that worked. I can submit a short PR to fix this in the template.

**Comment by sjoelund** [comment]
That would be great. Thanks.
