### ISSUE TITLE
Oudated class verson information

### ISSUE THREAD

**Issue by dietmarw** [modelica-association/conference-templates#8]
The modelica class still states:

     \ProvidesClass{modelica}[2015/05/20 v2.0 Modelica 2015 conference template]

This should be updated fixed for the **next** conference template (hence the Modelia2019 milestone)

**Comment by casella** [comment]
Oh boy, the number of items to be updated is uncountable. Could you please just change this to [Modelica Conference Template] without any further specification about dates?
